openapi: 3.0.0
info:
  description: "This is a web application to search breweries and add reviews."
  version: "1.0.0"
  title: "Brewery Review System API"

servers:
  - url: "http://localhost:5000"

paths:
  /signup:
    post:
      summary: "Sign up a new user"
      requestBody:
        description: "User object that needs to be added"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: "User created successfully"
        400:
          description: "Invalid input"
    
  /login:
    post:
      summary: "Login an existing user"
      requestBody:
        description: "User credentials"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        200:
          description: "User logged in successfully"
        401:
          description: "Invalid credentials"

  /logout:
    get:
      summary: "Logout the current user"
      responses:
        200:
          description: "User logged out successfully"

  /search:
    post:
      summary: "Search breweries"
      requestBody:
        description: "Search parameters"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchParams"
      responses:
        200:
          description: "Search results"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Brewery"
        400:
          description: "Invalid search parameters"

  /brewery/{id}:
    get:
      summary: "Get brewery details"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
        description: "ID of the brewery"
      responses:
        200:
          description: "Brewery details"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BreweryDetails"
        404:
          description: "Brewery not found"
    
    post:
      summary: "Add a review for the brewery"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
        description: "ID of the brewery"
      requestBody:
        description: "Review object"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Review"
      responses:
        201:
          description: "Review added successfully"
        400:
          description: "Invalid input"
        404:
          description: "Brewery not found"

components:
  schemas:
    User:
      type: "object"
      required:
        - "username"
        - "password"
      properties:
        username:
          type: "string"
        password:
          type: "string"

    UserCredentials:
      type: "object"
      required:
        - "username"
        - "password"
      properties:
        username:
          type: "string"
        password:
          type: "string"

    SearchParams:
      type: "object"
      required:
        - "search_by"
        - "search_value"
      properties:
        search_by:
          type: "string"
          enum:
            - "city"
            - "name"
            - "type"
        search_value:
          type: "string"

    Brewery:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        street:
          type: "string"
        city:
          type: "string"
        state:
          type: "string"
        phone:
          type: "string"
        website_url:
          type: "string"
        rating:
          type: "number"
          format: "float"

    BreweryDetails:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        street:
          type: "string"
        city:
          type: "string"
        state:
          type: "string"
        phone:
          type: "string"
        website_url:
          type: "string"
        reviews:
          type: "array"
          items:
            $ref: "#/components/schemas/Review"

    Review:
      type: "object"
      required:
        - "rating"
        - "description"
      properties:
        user_id:
          type: "integer"
        rating:
          type: "integer"
          format: "int32"
          minimum: 1
          maximum: 5
        description:
          type: "string"
